# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

### .env ###
#  MYSQL_ROOT_PASSWORD=
#  MYSQL_DATABASE=
#  MYSQL_USER=
#  MYSQL_PASSWORD=